config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :locations
  resources :organizations, except: [:index, :show,]
  resources :sessions, only: [:new, :create, :destroy]

  root 'locations#index'
  match '/users/new', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  get 'mission' =>'locations#mission'

  get 'contact' => 'locations#contact'

end

app/models/location.rb
# == Schema Information
#
# Table name: locations
#
#  id              :integer          not null, primary key
#  address         :string(255)
#  zipcode         :string(255)
#  state           :string(255)
#  city            :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  organization_id :integer
#

class Location < ActiveRecord::Base
  belongs_to :organization
  validates_presence_of :organization_id, :address, :zipcode, :state, :city
  geocoded_by :address
  after_validation :geocode #, if: ->(obj){ obj.address.present? and obj.address_changed? }
end


 def getFullAddress
   locations = Location.all
   a = []
     for i in locations
       a << "#{i.address} #{i.city}, #{i.state} #{i.zipcode} "
     end
     a
 end

 def address 
	[address, city, state, zipcode].compact.join(', ')
 end

def getEachOrg
   orgNames = Organization.all
   orgs = []
     for i in orgNames
        orgs << "#{i.name}"
     end
     orgs
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  website     :string(255)
#  telephone   :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  for_profit? :boolean
#  email       :string(255)
#

class Organization < ActiveRecord::Base
	has_many :locations, dependent: :destroy
	validates_uniqueness_of :name
	validates_presence_of :name

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :organization
  has_secure_password
  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates :email, presence: true, uniqueness: true
  validates :fname, presence: true
  validates :lname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @addressAmt = Location.all.length
    @fullAddress = getFullAddress
    @orgName = getOrgName
    @orgID = getOrgID
    # @mapInfo = getLocationInfo
    @orgName = getEachOrg
    @mapLats = getLatitudes
    @mapLngs = getLongitudes
        @location = Location.new
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new

  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    if @location.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Location has been added!' }
        format.js
      end
    else
      flash[:alert] = "Location cannot be added. Please make sure entire form is filled out."
      redirect_to root_path
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def mission
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :zipcode, :state, :city, :organization_id, :latitude, :longitude)
    end

    def getLatitudes
      locations = Location.all
      n = []
        for i in locations
          n << "#{i.latitude}"
        end
        n
    end

    def getLongitudes
      locations = Location.all
      n = []
        for i in locations
          n << "#{i.longitude}"
        end
        n
    end

    def getOrgName
      locations = Location.all
      n = []
        for i in locations
          n << "#{i.organization}"
        end
        n
    end

    def getOrgID
      locations = Location.all
      id = []
        for i in locations
          id<< "#{i.organization_id}"
        end
        id
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  

  def new
  		@org = Organization.new
  end

  def create
  		@org = Organization.new(org_params)
  		if @org.save
  			redirect_to new_location_path, notice: "New organization has been added."
  		else
	      flash[:alert] = "Org cannot be added. Please make sure to include an organization name."
        redirect_to new_organization_path
  		end
  end


  def edit
  end



  private

  def org_params
  		params.require(:organization).permit(:name, :website, :telephone, :for_profit?, :email)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title>Find-A-Bin</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <%= csrf_meta_tags %>
   <%= favicon_link_tag 'recycling_outline.png' %>
   <link href='http://fonts.googleapis.com/css?family=Comfortaa:700|Open+Sans' rel='stylesheet' type='text/css'>

   <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

   <script src="//code.jquery.com/jquery-1.10.2.js"></script>
   <script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
</head>
<body>
   <div class="wrapper">
      <div id="navbar">
         <div id="navLogo"><a href='/locations'>Find&nbsp;-<div id="recycle"><%= image_tag 'recycling_outline.png' %></div>-&nbsp;Bin</a></div>

         <ul id="navMenu">
            <li><%= link_to 'Mission', mission_path %></li>
            <li><%= link_to 'Locations', root_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
            <li> <%= link_to 'Add New Org', new_organization_path %></li>
         </ul>


	</div>
    <noscript><b>JavaScript must be enabled in order for you to use Google Maps.</b> 
      However, it seems JavaScript is either disabled or not supported by your browser. 
      To view Google Maps, enable JavaScript by changing your browser options, and then 
      try again.
    </noscript>

      <% if notice %> <p id="notice" class="x"><%= notice %> </p> <% end %>
   <% if alert %><p id="alert" class="x"><%= alert %></p> <% end %>
   
   
<div id="mainWrapper">
	<%= yield %>

      </div>
      <div class="push"></div>
   </div>

   <div class="footer">

      <p>&copy; 2014 Find A Bin, LLC</p>

   </div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  
  <div id="org-wrap">
 <%= collection_select(:location, :organization_id, Organization.all, :id, :name, prompt: true) %>
</div>

<br>
<div id="input-wrap">
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/locations/_list.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Zipcode</th>
      <th>State</th>
      <th>City</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.zipcode %></td>
        <td><%= location.state %></td>
        <td><%= location.city %></td>
        <td><%= location.organization_id %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/locations/contact.html.erb
    <div id="contact-wrap">
      <h1>Contact Us</h1><br>
       <form id="contact-us" action="" method="POST" enctype="multipart/form-data">
         <input name="action" value="submit" type="hidden"> Your name:<br>
         <input name="name" size="30" type="text"><br> Your email:<br>
         <input name="email" size="30" type="text"><br> Your message:<br>
         <textarea name="message" rows="7" cols="30"></textarea><br>
         <input value="Send email" type="submit">
      </form>
   </div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div id='map-wrap'>
	<h1>Find a Bin Near You!</h1>
		<div id="form-wrap">
			<h1 id="formTitle">Add New Bin Location</h1>
			<br/>

				<%= render 'form' %>

		</div>

		<div id="map-canvas"></div>


		<div id="filter">

			<ul>
				<% x = 1 %>

				<% @orgName.each do |o| %>
				
				<li>
					<%= check_box("tag", :"box#{x}", {checked: true}) %>
					<%= label_tag(:"box#{x}", "#{o}") %>
					<% x += 1 %>
				</li>

				<% end %>
			</ul>

		</div>
		
</div>


<!-- HIDDEN MAP MARKER INFORMATION. DO NOT TOUCH  -->

<div id="hiddenMapContent">


	<div id="addressAmt"> <%= @addressAmt %> </div>

	<div id="mapInfo">
	<h1> full addresses</h1>
		<% x = 0 %>
		<% @fullAddress.each do |m| %>
			<%= "<div id='fullAddress_#{x}'> #{m} </div>".html_safe %>
			<% x += 1 %>
		<% end %>
	</div>
<br/>
		<div id="markerLats">
		<h1> marker latitudes </h1>
		<% x = 0 %>
		<% @mapLats.each do |lat| %>
			<%= "<div id='latitude_#{x}'> #{lat} </div>".html_safe %>
			<% x += 1 %>

		<% end %>
	</div>
<br/>

	<div id="markerLngs">
	<h1> marker longitudes </h1>
		<% x = 0 %>
		<% @mapLngs.each do |lng| %>
			<%= "<div id='longitude_#{x}'> #{lng} </div>".html_safe %>
			<% x += 1 %>

		<% end %>
	</div>
<br/>

	<div id="locationOrgName">
	<h1> org names </h1>
		<% i = 0 %>
		<% @orgName.each do |n| %>
			<%="<div id='orgName_#{i}'> #{n} </div>".html_safe %>
			<% i += 1 %>
		<% end %>
	</div>

<br/>
	<div id="orgID">
	<h1> org ID </h1>
		<% i = 0 %>
		<% @orgID.each do |n| %>
			<%="<div id='orgID_#{i}'> #{n} </div>".html_safe %>
			<% i += 1 %>
		<% end %>
	</div>

</div>


<!-- END OF HIDDEN MAP CONTENT -->

app/views/locations/mission.html.erb
<div id="missionWrapper">

<div id="our-mission">
	<h2 id="mission">Our Mission</h2>
		<p>We aim to provide an opportunity for charities and businesses to exploit their clothing donation bins.</p>
</div>
<hr style="width: 600px; margin: 10px 0 20px -50px;">

<h2>Service</h2>
	<p>Our easy-to-use Web site allows donators to find clothing donation bins anywhere in NYC. We also partner with bin owners to help them promote their bin locations</p>

<h2>Bin Types</h2>
	<p>There are two types of clothing donation bins. Some are for charitable organizations while others are for for-profit businesses. Please understand the difference and donate to the bins that make you feel most comfortable.</p>

</div>

app/views/locations/new.html.erb
<br/>
<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @location.zipcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @location.state %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Organization:</strong>
  <%= @location.organization_id %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/mission/index.html.erb
<h1>Our Mission</h1>
<p>We aim to provide an opportunity for charities and businesses to exploit their clothing donation bins.</p>
<h2>Service</h2>
<p>Our easy to use Web site allows donators to find clothing donation bins anywhere in NYC. We also partner with bin owners to help them promote their bin locations</p>
<h2>Bin Types</h2>
<p>There are two types of clothign donation bins. Some are for charitable organizations while others are for for-profit businesses. Please understand the difference and donate to the bins that make you feel comfortable.</p>

app/views/organizations/edit.html.erb
<h1>Organizations#edit</h1>
<p>Find me in app/views/organizations/edit.html.erb</p>

app/views/organizations/new.html.erb
<h1>Add New Org</h1>
<br/>

	<% if notice %> <p id="notice" class="x"><%= notice %> </p> <% end %>
	<% if alert %><p id="alert" class="x"><%= alert %></p> <% end %>


<%= form_for(@org) do |f| %>
 <% if @org.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@org.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @org.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
	<%= radio_button_tag(:for_profit?, "true") %>
	<%= label_tag(:for_profit, "This org is for-profit.") %><br/>
	<%= radio_button_tag(:for_profit?, "false") %>
	<%= label_tag(:not_for_profit, "This org is not-for-profit.") %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </div>

  <div class="actions">
    <%= f.submit "Add Org" %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>